name: CI and CD to Render

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Check out code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Create empty SQLite database
            run: |
              touch ci.db
              echo "Temporary DB created."

          - name: Run tests
            run: pytest --verbose
            env:
              DATABASE_URL: ${{ secrets.DATABASE_URL }}


    deploy:
      needs: test
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
        - name: Trigger Render Deploy
          run: |
            curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
            